spring.application.name=task-manager

# Perfil ativo (dev = H2 local | prod = PostgreSQL)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configurações da API de IA (Groq)
ai.api.url=https://api.groq.com/openai/v1/chat/completions
ai.api.key=${AI_API_KEY:}
ai.api.model=llama-3.3-70b-versatile
